// Generated by CoffeeScript 1.9.0
(function() {
  var children, height, init, remove, svg, update, width;

  children = function(d) {
    var t, trans, _i, _len, _results;
    trans = [[-1, -1], [1, -1], [1, 1], [-1, 1]];
    _results = [];
    for (_i = 0, _len = trans.length; _i < _len; _i++) {
      t = trans[_i];
      _results.push({
        'x': d.x + d.r / 2 * t[0],
        'y': d.y + d.r / 2 * t[1],
        'r': d.r / 2
      });
    }
    return _results;
  };

  remove = function(el, data) {
    return data.splice(data.indexOf(el), 1);
  };

  update = function(data) {
    var circle;
    circle = svg.selectAll("circle").data(data);
    circle.enter().append("circle");
    circle.attr("cx", function(d) {
      return d.x;
    }).attr("cy", function(d) {
      return d.y;
    }).attr("r", function(d) {
      return d.r * 0.95;
    }).on('mouseover', function(d) {
      if (d.r > 2) {
        data = data.concat(children(d));
        remove(d, data);
        return update(data);
      }
    });
    return circle.exit().remove();
  };

  width = 500;

  height = 500;

  svg = d3.select("body").append("svg").attr("width", width).attr("height", height);

  init = [
    {
      'r': width / 2,
      'x': width / 2,
      'y': height / 2
    }
  ];

  update(init);

}).call(this);
